### ISSUE TITLE
Add a prisma_save() function

### ISSUE THREAD

**Issue by mcguinlu** [nealhaddaway/PRISMA2020#2]
Hi @nealhaddaway,

I think it would be worth adding a convience `prisma_save()` function to the package which takes the output of `PRISMA_flowchart()` and saves to a file - I just recommended the pacakge to a friend who wasn't sure how to save the resulting image.

**Comment by nealhaddaway** [comment]
This is a great point - I've tried and failed to get the 'Viewer' frame from R Studio to save the HTML output - it seems this isn't programmatically possible in a way that preserves the javascript appends... I'll leave this open in case someone can suggest a workaround.

**Comment by mcguinlu** [comment]
Hmmm, I've never worked with JS in R so don't know personally. But in this case it might be worth explaning the issues and describing best practice for saving the graphs one you have created them in R (which I am guessing is manually)?

**Comment by nealhaddaway** [comment]
Ooh - good idea. I'll write that in the documentation. Yeah you need to use the viewer in R Studio (no idea how GraphViz is handled in regular R, in fact...)

________________________________

**Comment by chriscpritchard** [comment]
In regular R, it just opens the HTML in your default browser, which works fine (fewer export options than RStudio has though...)

It would be nice to be able to generate SVG, PDF, PNG files as well as HTML... My reading of the code is that the JS appends generate the blue Included, Screening and Identification labels? Whilst this can't be done in graphViz (from my reading), it should be possible to include the ```<text>``` tags within the generated SVG/HTML using R instead of client-side Javascript.

I'm going to see if I can get this to work and if I can I'll submit a pull request.

**Comment by chriscpritchard** [comment]
Having done a little bit of tinkering, I've managed to get the labels rendering in graphviz rather than through additional client-side javascript (e7f63e9e46a876eeae3c98ad6dbdd1cd5b9502c7), this has some positives and negatives - the positives is the font etc is now consistent with the options defined when calling the function, the downside is that the text is vertical rather than rotated horizontally, because GraphViz doesn't support rotating labels you can emulate the functionality by inserting a newline between each character in the string like so:
```R
add_newline_between_chars_ <- function(x) {
    id_side_label <- gsub("(.)(?!$)", "\\1\n", x, perl=TRUE)
  }
```

I'm not sure this is the best way, because it's not brilliant for accessiblity as it generates a new ```<text>``` tag for each letter, but it is functional, and would make it possible to export programatically with labels intact.

The other way I can think of to export into an image would be to use something like selenium to launch a web browser to render the HTML, but that would need a a new browser window to be opened that would potentially need manually closing, aside from feeling a little broken, it wouldn't work very well with a headless install, or RMarkdown/Rnf/LaTeX files.

![image](https://user-images.githubusercontent.com/1839074/114322366-c107d080-9b17-11eb-90e1-a7772ee2fb4f.png)

**Comment by mcguinlu** [comment]
Hmmm, while this is a solid solution and removes the JS dependency, I find vertical text very hard to read - but maybe that is just me, we'll see what @nealhaddaway thinks!

Another option seems to be passing the labels as individual images which can then be rotated (as per the answer to [this SO question](https://stackoverflow.com/questions/55009159/change-label-orientation-90%C2%BA-of-a-node-in-graphviz)) - I just don't know enough about GraphViz in R to know if it will work here. . .

**Comment by chriscpritchard** [comment]
The vertical text bugs me too.. I think I've found a way of getting it to work though, although I've got a little more work to do, hopefully tonight or later in the week.

First of all I tidied up some of the javascript by using a switch statement instead of ifs, plus it means the injected JS is not having to be duplicated. Additionally, I was able to get the font and font size to be taken from the ```PRISMA_flowdiagram()``` function.

```R
  # Append in vertical text on blue bars
  switch (
    paste0(previous, other),
    'TRUETRUE' = {
      y = '19'
      node1x <- '537'
      node2x <- '356'
      node3x <- '95'
    },
    'FALSETRUE' = {
      y = '19'
      node1x <- '497'
      node2x <- '315'
      node3x <- '100'
    },
    'TRUEFALSE' = {
      y = '19'
      node1x <- '536'
      node2x <- '357'
      node3x <- '95'
    },
    'FALSEFALSE' = {
      y = '19'
      node1x <- '440'
      node2x <- '260'
      node3x <- '40'
    }
  )

  insertJS_ <- function (plot) {
    javascript <- htmltools::HTML(paste0('
      var theDiv = document.getElementById("node1");
      theDiv.innerHTML += "<text text-anchor=\'middle\' style=\'transform: rotate(-90deg);\' x=\'',node1x,'\' y=\'',y,'\' font-family=\'',font,',sans-Serif\' font-size=\'',fontsize,'\'>',id_side_label,'</text>";
      var theDiv = document.getElementById("node2");
      theDiv.innerHTML += "<text text-anchor=\'middle\' style=\'transform: rotate(-90deg);\' x=\'',node2x,'\' y=\'',y,'\' font-family=\'',font,',sans-Serif\' font-size=\'',fontsize,'\'>',scr_side_label,'</text>";
      var theDiv = document.getElementById("node3");
      theDiv.innerHTML += "<text text-anchor=\'middle\' style=\'transform: rotate(-90deg);\' x=\'',node3x,'\' y=\'',y,'\' font-family=\'',font,',sans-Serif\' font-size=\'',fontsize,'\'>',inc_side_label,'</text>";
    '))
    htmlwidgets::appendContent(plot, htmlwidgets::onStaticRenderComplete(javascript))
  }
  x <- insertJS_(x)
```

Then I've been tweaking the ```PRISMA_save()``` function, firstly I've added some output formats, along with the ability to customise the filename.

Currently the labels are missing, but that's because I haven't implemented the code yet to add them to the SVG.

The function works by either saving the HTML directly with:  ```htmlwidgets::saveWidget()``` which works absolutely fine as long as the HTML is loaded in a browser (as the embedded JS is then run) - this maintains the labels.

For other formats, I'm converting the DiagrammeR input into an SVG with ```DiagrammeRsvg```, which does everything nicely except the labels. Additionally, I'm extracting the JS appends into their own string using ```xml2``` and xpath, my plan is then to use xpath and ```xml2``` again to insert the ```<text>``` tags in the right place before finally saving the SVG (which can be converted to various formats using ```rsvg```, I think I've done the "hard" part so the rest should be reasonably straightforward string manipulation, and should mean we would have all the labels consistently displaying and rotated nicely.

The other thing I was thinking was perhaps making the labels along the top and side bold, as per the sample PRISMA2020 word document, rather than fixing the size of the side labels at 14, I think bold would look better and bring consistency!

**Comment by nealhaddaway** [comment]
Thanks very much, Chris - I also tried this solution, but I don't think vertical text is readable, really. I think RSelenium would be overkill.. Just seen your later comment - this sounds amazing!! Thanks so much. Will take some time to let you finish and digest it all :) Welcome to the team!

**Comment by chriscpritchard** [comment]
This is a PNG generated from the newly implemented ```PRISMA_Save()``` function. I can't get bold for labels working well, unfortunately, as I don't think the rendering engine used by ```DiagrammeR``` supports HTML tags in labels.

![PRISMA2020_flowdiagram](https://user-images.githubusercontent.com/1839074/114788721-e562e780-9d79-11eb-9cb6-05ef311343fe.png)

**Comment by chriscpritchard** [comment]
I was just wondering if you'd managed to get around to looking at this? I know it's likely super busy for everyone at the moment, so no worries if not!

**Comment by nealhaddaway** [comment]
Hi Chris - thanks so much. We love your suggestions - I'm so sorry for the delay, I've been struggling with COVID. I'm hoping to be fully back at work next week, so will try to get back to you once I've taken a look at your great code then. Thanks, Neal
________________________________

**Comment by chriscpritchard** [comment]
I hope you're feeling ok! No rush!

**Comment by mcguinlu** [comment]
@chriscpritchard, just to note that I have pulled this down locally to have a look, and aim to get back to you with any comments by tomorrow end of day.

CC @nealhaddaway for reference.
