### ISSUE TITLE
Unsure how to use PRISMA R package

### ISSUE THREAD

**Issue by mannyschwimmer** [nealhaddaway/PRISMA2020#24]
Hi there,
I'm new to R and unsure where to start in terms of creating PRISMA diagrams with this package. I looked through the files available on Github but didn't find a step-by-step guide. Without more guidance, I may not stand any chance of using this successfully. In case it helps you help me, I was hoping R could generate output like the shinyapp interactive HTML while also letting me customize its labels and add or manipulate bubbles. Some things I want to do include:

- Name the specific databases contributing to my search yield
- Indicate the reasons a prior review's studies were excluded and explicitly show the N excluded
- Present Key Question-specific yields below the overall N of included studies

I'll try tagging everyone I can in case it helps draw your attention here. Please be patient - I'm also new to posting on Github!
**@chriscpritchard @mcguinlu @nealhaddaway** 

Thanks in advance,
Manny

**Comment by nealhaddaway** [comment]
Hi Manny, I’m afraid what you want to do requires in depth knowledge of graphviz (the language underlying the package) - you can’t modify the broad structure of the flow diagram (intentionally) in the shiny app, and it’s not possible for us to make the R package customisable so broadly like that because of the complexity. We do plan to add database results per source for searching, but unfortunately can’t cater to everyone’s needs here, I’m sorry. My suggestion for very bespoke flow diagrams is to use the PowerPoint template that should be available on the PRISMA website.
Thanks
Neal

Sent from my iPhone

On 1 Dec 2021, at 21:58, mannyschwimmer ***@***.***> wrote:

﻿

Hi there,
I'm new to R and unsure where to start in terms of creating PRISMA diagrams with this package. I looked through the files available on Github but didn't find a step-by-step guide. Without more guidance, I may not stand any chance of using this successfully. In case it helps you help me, I was hoping R could generate output like the shinyapp interactive HTML while also letting me customize its labels and add or manipulate bubbles. Some things I want to do include:

  *   Name the specific databases contributing to my search yield
  *   Indicate the reasons a prior review's studies were excluded and explicitly show the N excluded
  *   Present Key Question-specific yields below the overall N of included studies

I'll try tagging everyone I can in case it helps draw your attention here. Please be patient - I'm also new to posting on Github!
@chriscpritchard<https://github.com/chriscpritchard> @mcguinlu<https://github.com/mcguinlu> @nealhaddaway<https://github.com/nealhaddaway>

Thanks in advance,
Manny

**Comment by chriscpritchard** [comment]
Hi,

I'm closing this as Neal identifies it requires in depth knowledge of the underlying architecture. Unfortunately, the development team don't have the capacity to provide that level of support, but hopefully you're able to find a solution to your issue.
