### ISSUE TITLE
PRISMA 2020 FLOW DIAGRAM

### ISSUE THREAD

**Issue by jenrola** [nealhaddaway/PRISMA2020#25]
Hi, 

Whenever I try to upload my edited csv template, the upload completes but then the page says "Disconnected from the server. Reload"?

**Comment by chriscpritchard** [comment]
Hi,

Do you have the capacity to try running it through the R code so we can see if there's an issue with the CSV as it may display an error message.

Chris

**Comment by jenrola** [comment]
Hi, 

I must admit I'm not familiar with R so I wouldn't know how to proceed in attempting to run in that way.

Jenrola

**Comment by chriscpritchard** [comment]
No problem - it's working for me when uploading a CSV file, so it might be something with your CSV file.

If you would like I can try and see what the issue is, but it would mean me needing a copy of the CSV. If you're happy to do that my email address is on my work profile (https://www.ntu.ac.uk/staff-profiles/social-sciences/chris-pritchard) - don't want to post it directly in comments to avoid spam bots!

Alternatively, if you have R installed the reference manual to this package is here: https://www.nealhaddaway.com/PRISMA2020/reference/index.html

**Comment by jenrola** [comment]
Great, I've sent you an email. 

Thanks!

**Comment by chriscpritchard** [comment]
just in case people stumble across this when searching - at the moment there isn't very graceful error handling in the shiny version of this app, so it tends to just not work without a descriptive error message. It's important that all fields (even if 0, or NA or aren't intending to be displayed) are included within the CSV file as otherwise the software can't fully import the CSV.
